### ISSUE TITLE
demo script broken?

### ISSUE THREAD

**Issue by power0341** [xingyizhou/pose-hg-3d#1]
hi @xingyizhou, thanks for providing this awesome project, however, I found that the demo.lua code seemed to not working properly, when I tried to execute the script, I got:
```
inconsistent tensor size, expected r_ [32], t [32] and src [2] to have the same number of elements, but got 32, 32 and 2 elements respectively

```

looks these lines of code incurred the problem, especially, the variable p returned from getPreds() with size (1,1,32), which crashed by p[1][j]:add(diff:sign():mul(.25))
 
```
  | local output = model:forward(inp:view(1, 3, inputRes, inputRes):cuda())
  | local tmpOutput = output[#output - 1]
  | local p = getPreds(tmpOutput)
  | local Reg = output[#output]
  | local z = (Reg + 1) * outputRes / 2
  | local pred = torch.zeros(J, 3)
  |  
  | for j = 1, J do
  | local hm = tmpOutput[1][j]
  | local pX, pY = p[1][j][1], p[1][j][2]
  | if pX > 1 and pX < outputRes and pY > 1 and pY < outputRes then
  | local diff = torch.FloatTensor({hm[pY][pX+1]-hm[pY][pX-1], hm[pY+1][pX]-hm[pY-1][pX]})
  | p[1][j]:add(diff:sign():mul(.25))
  | end
  | end
  | p:add(0.5)


```
I'm not quite familiar with LUA as well as Torch, so pls have a look.

**Comment by xingyizhou** [comment]
Hi power0341, 
  Sorry for the very delayed reply. Is the error still existing? I am not able to reproduce the error, what is your testing image?
