### ISSUE TITLE
Problem trying to run demo.lua on cpu

### ISSUE THREAD

**Issue by blackccpie** [xingyizhou/pose-hg-3d#12]
Hi,

I'm trying to run the demo.lua script in a cpu only configuration, with the following modifications:
- commenting gpu related _require_:
```lua
--require 'cunn'
--require 'cutorch'
--require 'cudnn'
```
- loading the model in a cpu compatible way:
```lua
local model = torch.load('../models/hgreg-3d.t7', map_location=lambda storage, loc: storage)
```
- removing reference to cuda:
```lua
local output = model:forward(inp:view(1, 3, inputRes, inputRes):float())--cuda())
```

Anyway I'm still getting the error `demo.lua:30: ')' expected near '='` when trying to run my modified code. Any ideas on what's going wrong?

Thanks for the help

**Comment by xingyizhou** [comment]
Hi, 
  Sorry for the late reply. Can you tell me what is your line 30?

**Comment by blackccpie** [comment]
Hi,

In fact I moved my experiments to your PyTorch implementation, and I gave up with this lua issue... so I guess I can close this bug.

Thanks anyway,

Albert
