### ISSUE TITLE
mpi-inf-3dhp annotations problem

### ISSUE THREAD

**Issue by rafikg** [xingyizhou/pose-hg-3d#13]
Hello,
Actually, I try to use this dataset and I have two questions : 
1) What is the difference between annot3 and annot3_univ? What the authors mean by (normalized) universal 3D pose? 
2) The annot3 projected on the 2D image plane are not equal to the 2D annotation ??
Exemple:

Let's take S1/Seq1 and camera 0 and frame 100.
intrincic camera  matrix : 
```
[[1.497693e+03 0.000000e+00 1.024704e+03]
 [0.000000e+00 1.497103e+03 1.051394e+03]
 [0.000000e+00 0.000000e+00 1.000000e+00]]
``` 
extrinsic camera matrix: 
```
[[ 9.650164e-01  4.880220e-03  2.621440e-01 -5.628666e+02]
 [-4.488356e-03 -9.993728e-01  3.512750e-02  1.398138e+03]
 [ 2.621510e-01 -3.507521e-02 -9.643893e-01  3.852623e+03]] 
```
perspective camera matrix: intrinsic X extrinsic: P 
```
[[ 1.71392549e+03 -2.86326367e+01 -5.95602339e+02  3.10479683e+06]
 [ 2.68904457e+02 -1.53304188e+03 -9.61363638e+02  6.14378130e+06]
 [ 2.62151000e-01 -3.50752100e-02 -9.64389300e-01  3.85262300e+03]]
```
project the 3D joint 0 from annotaiton_3D [28x3]
joint_0 = [ -18.0923  102.071  3726.17, 1  ] (# add 1 for homogeneous)
p2d = np.matmul(P, joint_0) and normalize by dividing by the 3rd element in p2d

**p2d = [3395.04400905 9569.4876827 ]**

ground truth 2d:

**[1017.43 1092.4 ]**

**Comment by rafikg** [comment]
@Gouiaa The annotations is given the camera's coordinate system. So, We don't need to use the extrinsic parameters.

**Comment by gh18l** [comment]
@Gouiaa So what is the difference between annot3 and annot3_univ? I found univ is not in the world's coordinate system.

**Comment by huangchaoxing** [comment]
@li19960612  Did you figure out the differences ?

**Comment by Realdr4g0n** [comment]
annotation_univ is described as 
`We make available both true 3D annotations, and a skeleton compatible with the “universal” skeleton of Human3.6m`

in this paper https://arxiv.org/pdf/1611.09813.pdf

**Comment by Vibhu04** [comment]
annot.mat: Body joint annotations in each camera's coordinate system. There are 2D pose annotations, 3D pose annotations and normalized 3D pose annotations (universal) available for each camera. For information about the joint order, joint labels and the joint subsets used in various projects, refer to mpii_get_joint_set. The file also contains the camera correspondence for each annotation cell (cameras, indexed with 0). For the camera subsets used in various projects, refer to mpii_get_camera_set. The 3D annotations (annot3) when reprojected into the image match the 2D annotations (annot2), however the same is not true of the normalized 3D annotations (univ_annot3). The 2D annotations (annot2) for each frame are arranged in a single row as x1,y1,x2,y2..,xj,yj, while the 3D annotations (annot3,univ_annot3) are arranged as x1,y1,z1,x2,y2,z2..,xj,yj,zj.. The file also contains the frame number correspondence for each row of annotations (frames). Though rare, it is possible that some sequences have a few frames missing at the end but annotations still available. Thus it is advisable to get the frame count F from mpii_get_sequence_info and read only the first F rows of annotations.

**Comment by danielajisafe** [comment]
> Though rare, it is possible that some sequences have a few frames missing at the end but annotations still available. Thus it is advisable to get the frame count F from mpii_get_sequence_info and read only the first F rows of annotations.

this part above is helpful, as Subject3 Sequence1 has n+1 poses, and n images.
