### ISSUE TITLE
Root = 8?

### ISSUE THREAD

**Issue by anuragmundhada** [xingyizhou/pose-hg-3d#2]
Hi, the root joint seems to change - here it is given as 8, but for evals 7 is being used. Possible bug?

https://github.com/xingyizhou/pose-hg-3d/blob/59fda670616ea4e13128bbef61e754f80e634e26/src/util/dataset/fusion.lua#L201

**Comment by xingyizhou** [comment]
Hi anuragmu, 
  Thanks for your careful reading the code. This is intended and not a bug. Not that we use different processing for generating the training samples and evaluation, for that in training and testing we have different meta-data. So they can be different. Using root 8 gives a better 2D-3D alignment in training, and using root 7 in testing is the standard protocol in other literature. 

Best, 
Xingyi

**Comment by anuragmundhada** [comment]
Thanks Xingyi for the prompt reply!
