### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by chenxuluo** [xingyizhou/pose-hg-3d#3]
Hi xingyi,  the output of the network is the 2D pixel locations and depths of each joint.  The depths seem to be rescaled and need alignment when computing the reconstruction error. Can you release your code for evaluating the MPJPE reported in the paper?  Thanks.

**Comment by xingyizhou** [comment]
Hi Chenxu, 
  Thanks for your interests on our work. This is a frequently asked question and actually the code is in https://github.com/xingyizhou/pose-hg-3d/blob/master/src/util/pose-hgreg-3d.lua#L156 . Note that both x, y, z are rescaled with the same scale in generating the training target. In training, (x, y) is in range 0~64 and z is in range(-1, 1). Directly do z = (z + 1) * 32 can convert (x, y, z) to the same space. For evaluation, we re-scale the output space to standardize the sum bone length (in https://github.com/xingyizhou/pose-hg-3d/blob/master/src/util/pose-hgreg-3d.lua#L178). MPJPE is directly calculated in this space. Note that the code produces slightly better results than we reported in the paper, for that we have correct some implementation detail after submission. 

Best, 
Xingyi

**Comment by chenxuluo** [comment]
Got it. Thanks for your reply.
Best,
Chenxu

**Comment by Colinsnow1** [comment]
Hi xingyi, I am also very confused about calculating the mpjpe shown as Table1 in the paper. And the code in src/utils/eval.py does not seem to be the final Evaluation code. So may you release the final evaluation code or any tips for final evaluation? Thanks!

**Comment by Ariel-JUAN** [comment]
@chenxuluo 
Hi, sorry to bother you. The output of depth is in range(-1, 1), does z = (z + 1) * 32 convert depth to image coordinate system? If I want to get the absolute depth (camera to people), what should I do?
Thanks!
