### ISSUE TITLE
How to prepare training/testing data for MPI-INF-3DHP dataset?

### ISSUE THREAD

**Issue by bearpaw** [xingyizhou/pose-hg-3d#5]
Hi Xingyi,

I just downloaded the MPI-INF-3DHP dataset (train and test), and try to understand how do you prepare the data for testing (or training) from `GetMPI-INF-3D.py`. However, the directories are not included in the original dataset:
```python
IMG_PATH = DATA_PATH + 'images/'
BBOX_PATH = DATA_PATH + 'MPI-INF-3DHP_crop_info/'
ANNOT2D_PATH = DATA_PATH + 'MPI-INF-3DHP_2d_annot/'
```

I guess these files are generated by you? Could you give me any hint on how do you use this dataset? Thank you very much!

**Comment by xingyizhou** [comment]
Hi Wei, 
  Actually those data is provided by the 3DHP authors. My version of 3DHP dataset is given directly by the authors and should be slightly different with their released version. However, the 2D bbox and 2D annotation is not used in this paper, so you can simply ignore them.

**Comment by bearpaw** [comment]
Hi Xingyi,

Thanks for your explanation. I converted the annotation from the original .mat files, and it works well!

**Comment by cbsudux** [comment]
Hi @bearpaw , could you share your code for converting the annotation from the original .mat files?
