### ISSUE TITLE
image pre-processing details

### ISSUE THREAD

**Issue by DeepRunner** [xingyizhou/pose-hg-3d#7]
Hi, xingyi,
In the data pre-processing stage, the bounding box of the original image is extracted via the function get_boundingbox() (which is not open source):
[https://github.com/xingyizhou/pose-hg-3d/blob/master/src/Tools/h36mPreprocessing.m#L137](https://github.com/xingyizhou/pose-hg-3d/blob/master/src/Tools/h36mPreprocessing.m#L137)
and then the original image is cropped by the bounding box.
Could you tell me the details about  the process that produced the bounding box with pose and camera parameters as input?

And in adjustbndbox() (which is not open source)
[https://github.com/xingyizhou/pose-hg-3d/blob/master/src/Tools/h36mPreprocessing.m#L181](https://github.com/xingyizhou/pose-hg-3d/blob/master/src/Tools/h36mPreprocessing.m#L181)
the bounding box is adjusted by the size of image, though the size of the bounding box has been secured to be smaller than the image. What is done in the function adjustbndbox()?

Thanks!

**Comment by xingyizhou** [comment]
Hi, 
  I didn't publish the data pre-processing code for that it is shared from another researcher and I didn't manage to fully re-write the code. I can send you a personal copy if you give me your email address. For the purpose of reproducing the results in the paper, you can use my processed data.

**Comment by DeepRunner** [comment]
Thank you, xingyi.
If possible, my email address is 2014300190@mail.nwpu.edu.cn
And I promise that the code is only for personal and academic usage.

**Comment by shanzg** [comment]
> Hi, xingyi.
I am a student who want to  reproduce the results in the paper. Could you send me a copy of the code? my email address is shanzg@buaa.edu.cn.

> I didn't publish the data pre-processing code for that it is shared from another researcher and I didn't manage to fully re-write the code. I can send you a personal copy if you give me your email address. For the purpose of reproducing the results in the paper, you can use my processed data.

hi,
