### ISSUE TITLE
pCKH score

### ISSUE THREAD

**Issue by EliMeirom** [xingyizhou/pose-hg-3d#9]
Hi,

In the paper it is stated that the performance after 60 training epochs was comparable to the reported results in the literature. 
Have you tested the pCKH score? Was this score degraded during the 3D training phase (stage 2 + 3)? 
What were the numeric results?

**Comment by xingyizhou** [comment]
Yes, it does degrade a little. If remembered correctly, it goes from 85% at stage 1 to 84% at stage 3 at mpii val. You can try the pytorch code yourself to see the exact number.
